from __future__ import annotations

from functools import wraps
from pathlib import Path
from typing import Any, Dict, Optional

try:
    from lazyllm import fc_register
except Exception:  # pragma: no cover - local debug fallback.
    def fc_register(*_args, **_kwargs):
        def _decorator(func):
            return func

        return _decorator

from chat.pptx.artifact import artifact_dir, save_artifact
from chat.pptx.parser import parse_pptx
from chat.pptx.qa import run_pptx_qa
from chat.pptx.renderer_python import render_deck_to_pptx
from chat.pptx.schema import normalize_deck_schema
from chat.pptx.thumbnails import render_pptx_thumbnails


def _tool_failure(tool_name: str, exc: Exception) -> Dict[str, Any]:
    return {
        'success': False,
        'reason': f'{tool_name} failed: {exc}',
        'error': str(exc),
        'error_type': type(exc).__name__,
    }


def _handle_tool_errors(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except Exception as exc:
            return _tool_failure(func.__name__, exc)

    return wrapper


def _safe_filename(filename: Optional[str], default: str = 'presentation.pptx') -> str:
    raw = str(filename or default).strip().replace('..', '').replace('\\', '/')
    raw = raw.rsplit('/', 1)[-1] or default
    if not raw.lower().endswith('.pptx'):
        raw += '.pptx'
    return raw


@fc_register('tool', execute_in_sandbox=False)
@_handle_tool_errors
def pptx_create_from_schema(deck_schema: Any, filename: str = 'presentation.pptx') -> Dict[str, Any]:
    """Create an editable PPTX file from a structured deck schema.

    Args:
        deck_schema: Dict or JSON string describing the deck. Recommended keys:
            title, subtitle, theme, slides. Each slide supports type, title,
            subtitle, bullets, left/right, table, evidence_refs.
        filename: Desired PPTX filename. The file is created under LazyRAG's
            upload root so it can be converted/served by later artifact tools.
    """
    normalized = normalize_deck_schema(deck_schema)
    out_dir = artifact_dir('pptx-work')
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / _safe_filename(filename)
    result = render_deck_to_pptx(normalized, out_path)
    result['deck_schema'] = normalized
    return result


@fc_register('tool', execute_in_sandbox=False)
@_handle_tool_errors
def pptx_parse(file_path: str) -> Dict[str, Any]:
    """Extract slide count, text, tables, image counts, and shape metadata from a PPTX file.

    Args:
        file_path: Absolute or relative path to a .pptx file generated by
            pptx_create_from_schema or provided by another tool.
    """
    return parse_pptx(file_path)


@fc_register('tool', execute_in_sandbox=False)
@_handle_tool_errors
def pptx_qa(file_path: str, deck_schema: Optional[Any] = None) -> Dict[str, Any]:
    """Run deterministic content/layout QA checks on a PPTX file.

    Args:
        file_path: Path to the .pptx file.
        deck_schema: Optional original deck schema. When provided, the QA checks
            whether expected titles/bullets/tables appear in the rendered PPTX.
    """
    return run_pptx_qa(file_path, deck_schema=deck_schema)


@fc_register('tool', execute_in_sandbox=False)
@_handle_tool_errors
def pptx_render_thumbnails(file_path: str, dpi: int = 144) -> Dict[str, Any]:
    """Render PPTX pages to PDF and PNG thumbnails for visual inspection.

    Args:
        file_path: Path to the .pptx file.
        dpi: Rendering DPI for thumbnails. 144 is a good default for QA.
    """
    return render_pptx_thumbnails(file_path, dpi=dpi, save_outputs=True)


@fc_register('tool', execute_in_sandbox=False)
@_handle_tool_errors
def artifact_save(file_path: str, kind: str = 'pptx', filename: Optional[str] = None) -> Dict[str, Any]:
    """Persist a generated file and return signed LazyRAG static-file URLs.

    Args:
        file_path: Local path to the generated file.
        kind: Artifact category under agent-results, e.g. pptx, pptx-preview.
        filename: Optional output filename to expose to users.
    """
    return save_artifact(Path(file_path), kind=kind, filename=filename)
